# Il reste 166 <persName> à indexer. Au boulot !
            DELETE FROM personnages;
        insert into personnages (id, nom, reference, segment) values('Cas_pers3','el Rey David','David','1');
      insert into personnages (id, nom, reference, segment) values('Cas_pers4','el Rey Salamón su fijo','Salomon','1');
      insert into personnages (id, nom, reference, segment) values('Cas_pers5','el Rey Salamón','Salomon','2');
      insert into personnages (id, nom, reference, segment) values('Cas_pers7','el Rey Sardanapalo','Sardanapale','3');
      insert into personnages (id, nom, reference, segment) values('Cas_pers14','el Rey Sardanapolo','Sardanapale','9');
      insert into personnages (id, nom, reference, segment) values('Cas_pers17','enperador Nero','Néron','11');
      insert into personnages (id, nom, reference, segment) values('Cas_pers22','Rey Alixandre','Alexandre le Grand','13');
      insert into personnages (id, nom, reference, segment) values('Cas_pers24','Rey Masmisma','Massinissa','14');
      insert into personnages (id, nom, reference, segment) values('Cas_pers27','Aníbal','Hannibal','15');
      insert into personnages (id, nom, reference, segment) values('Cas_pers29','Çipión','Scipion','15');
      insert into personnages (id, nom, reference, segment) values('Cas_pers34','Rey de Egipto, Antonio','Marc Antoine','16');
      insert into personnages (id, nom, reference, segment) values('Cas_pers36','Herodes','Hérodes','16');
      insert into personnages (id, nom, reference, segment) values('Cas_pers37','Otaviano','Octave','16');
      insert into personnages (id, nom, reference, segment) values('Cas_pers38','Cleopatra','Cléopâtre','16');
      insert into personnages (id, nom, reference, segment) values('Cas_pers39','la egibçiana','Cléopâtre','16');
      insert into personnages (id, nom, reference, segment) values('Cas_pers43','Cleopatra','Cléopâtre','16');
      insert into personnages (id, nom, reference, segment) values('Cas_pers44','Rey Salamón','Salomon','17');
      insert into personnages (id, nom, reference, segment) values('Cas_pers45','su fijo Roboán','Roboam','17');
      insert into personnages (id, nom, reference, segment) values('Cas_pers46','su siervo Geroboán','Jéroboam I','17');
      insert into personnages (id, nom, reference, segment) values('Cas_pers47','Rey Rodrigo','Rodrigue','18');
      insert into personnages (id, nom, reference, segment) values('Cas_pers48','don Yllán','Yllan','18');
      insert into personnages (id, nom, reference, segment) values('Cas_pers49','los Romanos','Peuple romain','19');
      insert into personnages (id, nom, reference, segment) values('Cas_pers51','Salamón','Salomon','21');
      insert into personnages (id, nom, reference, segment) values('Cas_pers52','David','David','21');
      insert into personnages (id, nom, reference, segment) values('Cas_pers53','Sansón','Sanson','21');
      insert into personnages (id, nom, reference, segment) values('Cas_pers58','Çipión Africano','Scipion l Africain','23');
      insert into personnages (id, nom, reference, segment) values('Cas_pers60','Rey Piro','Pyrrhus','24');
      insert into personnages (id, nom, reference, segment) values('Cas_pers62','los prínçipes Romanos','Princes Romains','25');
      insert into personnages (id, nom, reference, segment) values('Cas_pers64','los Romanos','Peuple romain','26');
      insert into personnages (id, nom, reference, segment) values('Cas_pers66','los sabios de Roma','Princes Romains','27');
      insert into personnages (id, nom, reference, segment) values('Cas_pers76','Vaspasiano','Vespasien','28');
      insert into personnages (id, nom, reference, segment) values('Cas_pers77','los cavalleros de Roma','Princes Romains','28');
      insert into personnages (id, nom, reference, segment) values('Cas_pers78','Vaspasiano','Vespasien','28');
      insert into personnages (id, nom, reference, segment) values('Cas_pers79','Rey sabio','Un roi sage','29');
      insert into personnages (id, nom, reference, segment) values('Cas_pers81','los Romanos','Peuple romain','31');
      insert into personnages (id, nom, reference, segment) values('Cas_pers82','Rey de los Reyes','Jésus','32');
      insert into personnages (id, nom, reference, segment) values('Cas_pers83','señor de los señores','Jésus','32');
      insert into personnages (id, nom, reference, segment) values('Cas_pers89','Yhesú Cristo','Jésus','33');
      insert into personnages (id, nom, reference, segment) values('Cas_pers95','Serses','Xerxès','34');
      insert into personnages (id, nom, reference, segment) values('Cas_pers101','los Romanos','Peuple romain','34');
      insert into personnages (id, nom, reference, segment) values('Cas_pers109','los enperadores','Princes Romains','36');
      insert into personnages (id, nom, reference, segment) values('Cas_pers110','Alixandre','Alexandre le Grand','37');
      insert into personnages (id, nom, reference, segment) values('Cas_pers113','Çesar','César','38');
      insert into personnages (id, nom, reference, segment) values('Cas_pers115','los rromanos','Peuple romain','39');
      insert into personnages (id, nom, reference, segment) values('Cas_pers116','los Romanos','Peuple romain','40');
      insert into personnages (id, nom, reference, segment) values('Cas_pers118','los Romanos','Peuple romain','40');
      insert into personnages (id, nom, reference, segment) values('Cas_pers119','Quinaçio','Cincinnatus','41');
      insert into personnages (id, nom, reference, segment) values('Cas_pers125','Quinaçio','Cincinnatus','41');
      insert into personnages (id, nom, reference, segment) values('Cas_pers127','los Romanos','Peuple romain','41');
      insert into personnages (id, nom, reference, segment) values('Cas_pers128','las mugeres de aquél tienpo','Femmes (collectif)','42');
      insert into personnages (id, nom, reference, segment) values('Cas_pers129','los omnes','Hommes (collectif)','42');
      insert into personnages (id, nom, reference, segment) values('Cas_pers130','las mugeres','Femmes (collectif)','42');
      insert into personnages (id, nom, reference, segment) values('Cas_pers131','Noe','Noé','42');
      insert into personnages (id, nom, reference, segment) values('Cas_pers133','Sanson','Sanson','43');
      insert into personnages (id, nom, reference, segment) values('Cas_pers135','los Filisteos','Les Philistins','43');
      insert into personnages (id, nom, reference, segment) values('Cas_pers138','los Filisteos','Les Philistins','43');
      insert into personnages (id, nom, reference, segment) values('Cas_pers139','Dalida','Dalila','43');
      insert into personnages (id, nom, reference, segment) values('Cas_pers141','Absalon','Absalom','44');
      insert into personnages (id, nom, reference, segment) values('Cas_pers144','el rrey David','David','44');
      insert into personnages (id, nom, reference, segment) values('Cas_pers146','el Rey David','David','44');
      insert into personnages (id, nom, reference, segment) values('Cas_pers147','Joab','Joab','44');
      insert into personnages (id, nom, reference, segment) values('Cas_pers148','Davit','David','44');
      insert into personnages (id, nom, reference, segment) values('Cas_pers149','Digna','Digna','45');
      insert into personnages (id, nom, reference, segment) values('Cas_pers150','Jacob','Jacob','45');
      insert into personnages (id, nom, reference, segment) values('Cas_pers151','Tamar','Tamar','46');
      insert into personnages (id, nom, reference, segment) values('Cas_pers152','Davit','David','46');
      insert into personnages (id, nom, reference, segment) values('Cas_pers153','Amón','Amon','46');
      insert into personnages (id, nom, reference, segment) values('Cas_pers155','Absalón','Absalom','46');
      insert into personnages (id, nom, reference, segment) values('Cas_pers156','Santa Catalina','Sainte Catherine','47');
      insert into personnages (id, nom, reference, segment) values('Cas_pers157','Casto','Casto','47');
      insert into personnages (id, nom, reference, segment) values('Cas_pers158','Masençio','Maxence (empereur)','47');
      insert into personnages (id, nom, reference, segment) values('Cas_pers162','Muysé','Moïse','49');
      insert into personnages (id, nom, reference, segment) values('Cas_pers163','David','David','49');
      insert into personnages (id, nom, reference, segment) values('Cas_pers166','Costantyno','Constantin (empereur)','50');
      insert into personnages (id, nom, reference, segment) values('Cas_pers168','Constantyno','Constantin (empereur)','50');
      insert into personnages (id, nom, reference, segment) values('Cas_pers169','los cavalleros Romanos','Princes Romains','50');
      insert into personnages (id, nom, reference, segment) values('Cas_pers170','el enperador','Constantin (empereur)','50');
      insert into personnages (id, nom, reference, segment) values('Cas_pers172','Theodosio','Théodose (empereur)','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers173','enperador sobre dicho','Théodose (empereur)','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers174','Sant Anbrosio','Saint Ambroise','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers175','el enperador','Théodose (empereur)','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers176','el enperador','Théodose (empereur)','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers177','el Santo obispo','Saint Ambroise','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers178','enperador','Constantin (empereur)','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers179','Rrufino','Rufin','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers182','Sant Anbrosio','Saint Ambroise','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers183','Sant Anbrosio','Saint Ambroise','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers184','Rrufino','Rufin','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers185','Sant Anbrosio','Saint Ambroise','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers186','el enperador','Théodose (empereur)','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers187','Sant Anbrosio','Saint Ambroise','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers188','el enperador','Théodose (empereur)','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers189','Sant Anbrosio','Saint Ambroise','51');
      insert into personnages (id, nom, reference, segment) values('Cas_pers190','este devoto enperador','Théodose (empereur)','52');
      insert into personnages (id, nom, reference, segment) values('Cas_pers191','Constantino','Constantin (empereur)','53');
      insert into personnages (id, nom, reference, segment) values('Cas_pers193','Constantyno','Constantin (empereur)','53');
      insert into personnages (id, nom, reference, segment) values('Cas_pers194','Theodosio','Théodose (empereur)','54');
      insert into personnages (id, nom, reference, segment) values('Cas_pers195','Dios','Dieu','54');
      insert into personnages (id, nom, reference, segment) values('Cas_pers196','Dios','Dieu','54');
      insert into personnages (id, nom, reference, segment) values('Cas_pers198','Dios','Dieu','54');
      insert into personnages (id, nom, reference, segment) values('Cas_pers199','Dios','Dieu','55');
      insert into personnages (id, nom, reference, segment) values('Cas_pers200','los rromanos','Peuple romain','57');
      insert into personnages (id, nom, reference, segment) values('Cas_pers201','Anibal','Hannibal','58');
      insert into personnages (id, nom, reference, segment) values('Cas_pers202','los rromanos','Peuple romain','58');
      insert into personnages (id, nom, reference, segment) values('Cas_pers203','los rromanos','Peuple romain','58');
      insert into personnages (id, nom, reference, segment) values('Cas_pers204','Alixandre','Alexandre le Grand','59');
      insert into personnages (id, nom, reference, segment) values('Cas_pers206','los cavalleros rromanos','Peuple romain','60');
      insert into personnages (id, nom, reference, segment) values('Cas_pers208','los rromanos','Peuple romain','61');
      insert into personnages (id, nom, reference, segment) values('Cas_pers209','los rromanos','Peuple romain','61');
      